### ISSUE TITLE
Cannot find module 'process'

### ISSUE THREAD

**Issue by jgf5013** [systemjs/plugin-css#106]
**Issue**
importing with plugin-css@0.1.27, as below, throws an error when using jspm api to run jspm.bundle
`import './example.css!css';`

**Resulting Error**
```
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at p (C:/workspace/application_folder/jspm_packages/github/systemjs/plugin-css@0.1.27/clean-css.js:1:3118)
```

**Resolution**
Downgrading to v0.1.26 solved the issue for me

**Other Details**
npm version: 3.10.2

**Comment by guybedford** [comment]
Make sure you are you using NodeJS v6 for this support.
