### ISSUE TITLE
how to pass tests

### ISSUE THREAD

**Issue by amenadiel** [systemjs/plugin-css#129]
In a clean clone of this repo, I ran

```sh
npm install
npm run build
npm test
```

And it fails 3 of 4 tests:

```sh
  1) Node: Integration Should output css bundle:
     Error: ENOENT: no such file or directory, open 'jspm_packages/npm/svgo@0.7.1/lib/svgo/../../.svgo.yml'
      at Error (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.readFileSync (fs.js:502:33)
      at module.exports (file://postcss-bundle.js:16802:52)
      at new module.exports (file://postcss-bundle.js:20503:23)
      at file://postcss-bundle.js:20708:20
      at Object.creator [as postcssSvgo] (file://postcss-bundle.js:166789:37)
      at file://postcss-bundle.js:156147:44
      at Array.forEach (native)
      at file://postcss-bundle.js:156134:33
      at creator (file://postcss-bundle.js:166789:37)
      at SystemJSNodeLoader.exports.bundle (file://css-plugin-base-builder.js:140:25)
      at file://css-plugin-base.js:44:27

  2) Node: Integration Should compile css with rootURL:
     Error: ENOENT: no such file or directory, open 'jspm_packages/npm/svgo@0.7.1/lib/svgo/../../.svgo.yml'
      at Error (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.readFileSync (fs.js:502:33)
      at module.exports (file://postcss-bundle.js:16802:52)
      at new module.exports (file://postcss-bundle.js:20503:23)
      at file://postcss-bundle.js:20708:20
      at Object.creator [as postcssSvgo] (file://postcss-bundle.js:166789:37)
      at file://postcss-bundle.js:156147:44
      at Array.forEach (native)
      at file://postcss-bundle.js:156134:33
      at creator (file://postcss-bundle.js:166789:37)
      at SystemJSNodeLoader.exports.bundle (file://css-plugin-base-builder.js:140:25)
      at file://css-plugin-base.js:44:27

  3) Node: Integration Should support separateCSS: true and sourceMaps: false:
     Error: ENOENT: no such file or directory, open 'jspm_packages/npm/svgo@0.7.1/lib/svgo/../../.svgo.yml'
      at Error (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.readFileSync (fs.js:502:33)
      at module.exports (file://postcss-bundle.js:16802:52)
      at new module.exports (file://postcss-bundle.js:20503:23)
      at file://postcss-bundle.js:20708:20
      at Object.creator [as postcssSvgo] (file://postcss-bundle.js:166789:37)
      at file://postcss-bundle.js:156147:44
      at Array.forEach (native)
      at file://postcss-bundle.js:156134:33
      at creator (file://postcss-bundle.js:166789:37)
      at SystemJSNodeLoader.exports.bundle (file://css-plugin-base-builder.js:140:25)
      at file://css-plugin-base.js:44:27
```

Am I doing something wrong? Perhaps something changed in svgo? Something that requires an additional mapping to include `.svgo.yml` in the build?

**Comment by guybedford** [comment]
I don't think the build here has been tested since jspm 0.17.0-beta.14, so there may have been a regression in the build process itself.
