### ISSUE TITLE
CSS bundling broken with current package dependencies

### ISSUE THREAD

**Issue by rpkilby** [systemjs/plugin-css#29]
After running `jspm update`, bundling CSS seems to have broken. SystemJS in the browser continues to work as expected, but `jspm bundle` generates the following exception:
```
err  TypeError: Arguments to path.join must be strings
         at path.js:360:15
         at Array.filter (native)
         at Object.exports.join (path.js:358:36)
         at originalPositionIn (evalmachine.<anonymous>:120:140)
         at InputSourceMapStore.originalPositionFor (evalmachine.<anonymous>:189:12)
         at snapshot (evalmachine.<anonymous>:55:41)
         at track (evalmachine.<anonymous>:111:5)
         at Object.context.track (evalmachine.<anonymous>:23:16)
         at Object.Extractors.properties (evalmachine.<anonymous>:37:46)
         at tokenize (evalmachine.<anonymous>:177:26)
```

After fiddling with the testlibs project in jspm-cli, it seems traceable to the 3.2.x release of clean-css:
- clone jspm-cli
- cd into testlibs
- `jspm install`
- `jspm update npm:clean-css` (installs 3.2.x)
- `jspm bundle main`

The bundle command throws the above exception. Downgrading to clean-css ~3.1.x seemed to fix the issue.

**Comment by edrex** [comment]
I hit this as well. Bundling is actually working for me with simple CSS files, but is definitely broken with bootstrap.css

### Steps to reproduce:

```shell
jspm init -y
jspm install css bootstrap
echo "import _ from 'bootstrap/css/bootstrap.css!';" > app.js
jspm bundle app app-build.js
```

### Result:

```
Building the bundle tree for app...

  app
  github:twbs/bootstrap@3.3.4/css/bootstrap.css!github:systemjs/plugin-css@0.1.9


err  TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at originalPositionIn (evalmachine.<anonymous>:120:140)
    at InputSourceMapStore.originalPositionFor (evalmachine.<anonymous>:189:12)
    at snapshot (evalmachine.<anonymous>:55:41)
    at track (evalmachine.<anonymous>:111:5)
    at Object.context.track (evalmachine.<anonymous>:23:16)
    at Object.Extractors.properties (evalmachine.<anonymous>:37:46)
    at tokenize (evalmachine.<anonymous>:177:26)
```

Downgrading to `clean-css@~3.1.0` fixes the problem for me as well:

```
jspm install npm:clean-css@~3.1.0
jspm bundle app app-build.js
# runs successfully
```

**Comment by guybedford** [comment]
Thanks - I've pushed out a 0.1.10 that locks back the clean-css version for now until we can include a better fix.

**Comment by crisptrutski** [comment]
Unneeded if #22 is the direction taken
