### ISSUE TITLE
Cant bundle,  Unable to calculate canonical name

### ISSUE THREAD

**Issue by henkv** [systemjs/plugin-css#68]
Hello, I've ran into a build error i dont know what to do with and a link to the current branch
https://github.com/henkv/wuxia-feed/tree/sqlite

    err  Error: CSS Plugin:
         Broken @import declaration of "jspm_packages\github\systemjs\plugin-css@0.1.20\app.css"
         Broken @import declaration of "jspm_packages\github\systemjs\plugin-css@0.1.20\FeedList.css"
         Broken @import declaration of "jspm_packages\github\systemjs\plugin-css@0.1.20\FeedItem.css"
         Broken @import declaration of "jspm_packages\github\systemjs\plugin-css@0.1.20\FeedEdit.css"
             at file:///C:/Users/henkv/Documents/GitHub/wuxia-feed/client/jspm_packages/github/systemjs/plugin-css@0.1.20/css-builder.js:76:13

**Comment by henkv** [comment]
I had a path named css in my config.js i removed that and now it wont pass the first build step

         Building the bundle tree for js/app.js...                                                                             
                                                                                                                               
    err  Error tracing js/app.js at file:///C:/Users/henkv/Documents/GitHub/wuxia-feed/client/js/app.js                        
            Error: Unable to calculate canonical name to bundle file:///css/app.css                                            
             at getCanonicalNamePlain (C:\Users\henkv\Documents\GitHub\wuxia-feed\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:191:13)                                                                                                    
             at getCanonicalName (C:\Users\henkv\Documents\GitHub\wuxia-feed\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:102:19)                                                                                                         
             at getCanonicalName (C:\Users\henkv\Documents\GitHub\wuxia-feed\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:94:12)                                                                                                          
             at C:\Users\henkv\Documents\GitHub\wuxia-feed\node_modules\jspm\node_modules\systemjsbuilder\lib\trace.js:375:34

**Comment by guybedford** [comment]
That fact that it is trying to load `file:///css/app.css` from the root of the filesystem looks odd here. Did you use a path like `/css/app.css`?

**Comment by henkv** [comment]
Yes 
`import "/css/app.css!";`

**Comment by guybedford** [comment]
@henkv URLs of that form won't build due to the fact that when running in Node `import "/x"` means importing from the root of the file system. We have no mechanism to alter the "root" in builds, only the baseURL (`import "x"` over import "/x"`).
